# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 346)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(40, 30, 321, 290))
        self.frame_2.setMinimumSize(QtCore.QSize(40, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(500, 600))
        self.frame_2.setStyleSheet("\n"
"QFrame#frame_2{\n"
"background-color: rgb(209, 209, 209);\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(1, 30, 319, 259))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(94, 94, 94);\n"
"border: 0.5px solid rgb(209, 209, 209);;\n"
"border-bottom-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(1, 59, 321, 1))
        self.line.setStyleSheet("background-color: rgb(108, 108, 108);")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 231, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(211, 211, 211);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(211, 211, 211);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self._2 = QtWidgets.QVBoxLayout()
        self._2.setObjectName("_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);font: 63 7pt \"Bahnschrift SemiBold\";\n"
"color: rgb(236, 236, 236);}\n"
"QLineEdit#lineEdit_2:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);font: 63 8pt \"Bahnschrift SemiBold\";\n"
"color: rgb(236, 236, 236);}")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self._2.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("QLineEdit#lineEdit{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);font: 63 7pt \"Bahnschrift SemiBold\";\n"
"color: rgb(236, 236, 236);}\n"
"QLineEdit#lineEdit:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);font: 63 8pt \"Bahnschrift SemiBold\";\n"
"color: rgb(236, 236, 236);}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self._2.addWidget(self.lineEdit)
        self.horizontalLayout.addLayout(self._2)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(250, 60, 71, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 8, 301, 47))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.create = QtWidgets.QPushButton(self.layoutWidget2)
        self.create.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.create.setFont(font)
        self.create.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-radius: 5px;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgba(0, 151, 193, 240);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     border-radius: 5px;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(237, 95, 95);\n"
"}")
        self.create.setObjectName("create")
        self.horizontalLayout_2.addWidget(self.create)
        self.settings = QtWidgets.QPushButton(self.layoutWidget2)
        self.settings.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.settings.setFont(font)
        self.settings.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-radius: 5px;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(156, 156, 156);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     border-radius: 5px;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(189, 189, 189);\n"
"}")
        self.settings.setObjectName("settings")
        self.horizontalLayout_2.addWidget(self.settings)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border-radius: 5px;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(156, 156, 156);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"     border-radius: 5px;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(189, 189, 189);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 211, 29))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(266, 0, 55, 29))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    image: url(:/image/close (6).png);\n"
"border-top-right-radius: 5px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:none;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(255, 49, 49);\n"
"    image: url(:/image/close (5).png);\n"
"border-top-right-radius: 5px;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border:none;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(255, 137, 137);\n"
"border-top-right-radius: 5px;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(3, 30, 315, 1))
        self.line_2.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(211, 0, 55, 29))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    image: url(:/image/minimize (5).png);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border:none;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(134, 134, 134);\n"
"    image: url(:/image/minimize (6).png);\n"
"\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border:none;\n"
"    color: rgb(224, 224, 224);\n"
"    background-color: rgb(179, 179, 179);\n"
"    image: url(:/image/minimize (6).png);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Width"))
        self.label.setText(_translate("MainWindow", "Height"))
        self.lineEdit_2.setText(_translate("MainWindow", "640"))
        self.lineEdit.setText(_translate("MainWindow", "640"))
        self.checkBox.setText(_translate("MainWindow", "Hide"))
        self.checkBox_2.setText(_translate("MainWindow", "Labeling"))
        self.create.setText(_translate("MainWindow", "Create"))
        self.settings.setText(_translate("MainWindow", "Settings"))
        self.pushButton_3.setText(_translate("MainWindow", "Annotation"))

import Icon.icon_rc