# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Rect_ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 232)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 981, 871))
        self.frame.setMinimumSize(QtCore.QSize(981, 871))
        self.frame.setMaximumSize(QtCore.QSize(981, 871))
        self.frame.setMouseTracking(True)
        self.frame.setAcceptDrops(False)
        self.frame.setStyleSheet("background-color: rgb(164, 164, 164);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.dockWidget = QtWidgets.QDockWidget(self.frame)
        self.dockWidget.setGeometry(QtCore.QRect(10, 390, 211, 291))
        self.dockWidget.setMouseTracking(True)
        self.dockWidget.setStyleSheet("\n"
"background-color: rgb(205, 205, 205);")
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMouseTracking(True)
        self.dockWidgetContents.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(110, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 106, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton_5:hover{\n"
"border-radius:5px;\n"
"background-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 180, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalSlider = QtWidgets.QSlider(self.dockWidgetContents)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 111, 80, 16))
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.horizontalSlider.setMouseTracking(True)
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid;\n"
"    height: 2px;\n"
"    margin: 0px;\n"
"    }\n"
"QSlider::handle:horizontal {\n"
"background-color: rgb(255, 255, 255);\n"
"    border: 1px solid;\n"
"    height: 40px;\n"
"    width: 6px;\n"
"    margin: -5px 0px;\n"
"    }")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(20)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setSliderPosition(2)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_6 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 106, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton#pushButton_6{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton_6:hover{\n"
"border-radius:5px;\n"
"background-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(11, 62, 81, 25))
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"border-radius:5px;\n"
"background-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_3:menu-indicator{width:0px;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_4.setGeometry(QtCore.QRect(111, 62, 81, 25))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton_4:hover{\n"
"border-radius:5px;\n"
"background-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(111, 17, 81, 25))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"border-radius:5px;\n"
"background-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.dockWidgetContents)
        self.checkBox.setGeometry(QtCore.QRect(10, 150, 81, 25))
        self.checkBox.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(11, 17, 81, 25))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.pushButton.setAcceptDrops(True)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"border-radius:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"border-radius:5px;\n"
"background-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton:menu-indicator{width:0px;}")
        self.pushButton.setObjectName("pushButton")
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.dockWidget_3 = QtWidgets.QDockWidget(self.frame)
        self.dockWidget_3.setGeometry(QtCore.QRect(600, 400, 261, 301))
        self.dockWidget_3.setMouseTracking(True)
        self.dockWidget_3.setFloating(False)
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_3.setWindowTitle("")
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.dockWidgetContents_3)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 261, 281))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setMouseTracking(True)
        self.listWidget_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.listWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_2.setObjectName("listWidget_2")
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 70, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPixelSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"border-radius: 5px")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(300, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border-radius: 4px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"border-radius: 4px;\n"
"    background-color: rgb(183, 183, 183);\n"
"padding-bottom: 3px;\n"
"}\n"
"QPushButton:pressed{\n"
"border-radius: 4px;\n"
"    background-color: rgb(219, 219, 219);\n"
"padding-top: 3px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "2"))
        self.pushButton_5.setText(_translate("Form", "Cir Pen Width"))
        self.lineEdit_2.setText(_translate("Form", "2"))
        self.pushButton_6.setText(_translate("Form", "Circle Radius"))
        self.pushButton_3.setText(_translate("Form", "Color"))
        self.pushButton_4.setText(_translate("Form", "Brush Color"))
        self.pushButton_2.setText(_translate("Form", "Rect Pen Width"))
        self.checkBox.setText(_translate("Form", "Brush"))
        self.pushButton.setText(_translate("Form", "Shape"))
        self.pushButton_7.setText(_translate("Form", "Confirm"))
