# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(551, 591)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(551, 591))
        Form.setMaximumSize(QtCore.QSize(551, 591))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 551, 591))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(94, 94, 94);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 530, 181, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPixelSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton#pushButton_4{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(126, 126, 126);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_4:hover{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(155, 155, 155);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_4:pressed{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(183, 183, 183);\n"
"    border-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPixelSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(139, 139, 139);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(155, 155, 155);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(183, 183, 183);\n"
"    border-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPixelSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(0, 107, 157);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(0, 122, 179);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(0, 144, 211);\n"
"    border-color: rgb(192, 192, 192);\n"
"}\n"
"QPushButton#pushButton_2:disabled{\n"
"    color: rgb(230, 230, 230);\n"
"     border-width: 1px;\n"
"     border-radius: 5px;\n"
"border-style: solid;\n"
"     padding: 6px;\n"
"    background-color: rgb(210, 210, 210);\n"
"    border-color: rgb(192, 192, 192);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 11, 531, 501))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(72, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 52))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit#lineEdit{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);\n"
"color: rgb(236, 236, 236);\n"
"}\n"
"color: rgb(217, 217, 217);\n"
"QLineEdit#lineEdit:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(12, 12))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton#pushButton_10{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_10:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_10:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit#lineEdit_6{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);\n"
"color: rgb(236, 236, 236);}\n"
"QLineEdit#lineEdit_6:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);\n"
"color: rgb(236, 236, 236);}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_8.addWidget(self.lineEdit_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton#pushButton_7{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_7:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_7:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton#pushButton_9{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_9:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_9:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit#lineEdit_2{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);\n"
"color: rgb(236, 236, 236);\n"
"}\n"
"QLineEdit#lineEdit_2:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);\n"
"color: rgb(236, 236, 236);}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(70, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPixelSize(8)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox{border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);}\n"
"QComboBox:hover{border-radius: 5px;\n"
"background-color: rgb(214, 214, 214);\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(71, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit#lineEdit_4{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);\n"
"color: rgb(236, 236, 236);}\n"
"QLineEdit#lineEdit_4:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);\n"
"color: rgb(236, 236, 236);}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_6.addWidget(self.lineEdit_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton#pushButton_6{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_6:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_6:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton#pushButton_8{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_8:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_8:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit#lineEdit_3{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);\n"
"color: rgb(236, 236, 236);}\n"
"QLineEdit#lineEdit_3:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);\n"
"color: rgb(236, 236, 236);}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit#lineEdit_7{border-radius: 5px;     padding: 6px;    background-color: rgb(143, 143, 143);\n"
"color: rgb(236, 236, 236);}\n"
"QLineEdit#lineEdit_7:hover{border-radius: 5px;\n"
"background-color: rgb(169, 169, 169);\n"
"color: rgb(236, 236, 236);}")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton#pushButton_11{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_11:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_11:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton#pushButton_12{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_12:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_12:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPixelSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
"border-radius: 3px;background-color: rgb(177, 177, 177);\n"
"}\n"
"QPushButton#pushButton_5:hover{\n"
"border-radius: 3px;    \n"
"    background-color: rgb(191, 197, 197);\n"
"}\n"
"QPushButton#pushButton_5:pressed{\n"
"border-radius: 3px;\n"
"    background-color: rgb(213, 213, 213);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPixelSize(7)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setMouseTracking(True)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border:none;")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setMaximumSize(QtCore.QSize(800, 15))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPixelSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 7px;\n"
"border: 1px solid;\n"
"border-width:1.5px;\n"
"    border-color: rgb(51, 51, 51);\n"
"background-color: rgb(223, 223, 223);\n"
"\n"
"}\n"
"QProgressBar:chunk{\n"
"color: rgb(236, 236, 236);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 161, 118);\n"
"}\n"
"")
        self.progressBar.setProperty("value", 50)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Setting"))
        self.pushButton_4.setText(_translate("Form", "Ok"))
        self.pushButton_3.setText(_translate("Form", "Cancel"))
        self.pushButton_2.setText(_translate("Form", "Apply"))
        self.label.setText(_translate("Form", "Srceenshot Location:"))
        self.lineEdit.setText(_translate("Form", "123"))
        self.label_8.setText(_translate("Form", "Data Augment Load:"))
        self.label_2.setText(_translate("Form", "Saving Name:"))
        self.lineEdit_2.setText(_translate("Form", "Image"))
        self.label_9.setText(_translate("Form", "Quality:"))
        self.label_7.setText(_translate("Form", "Format:"))
        self.comboBox_2.setItemText(0, _translate("Form", "JPG"))
        self.comboBox_2.setItemText(1, _translate("Form", "PNG"))
        self.comboBox_2.setItemText(2, _translate("Form", "TIFF"))
        self.comboBox_2.setItemText(3, _translate("Form", "BMP"))
        self.comboBox_2.setItemText(4, _translate("Form", "JP2"))
        self.label_6.setText(_translate("Form", "Augment Images Location:"))
        self.label_5.setText(_translate("Form", "Augment Image Name:"))
        self.label_10.setText(_translate("Form", "Labeling Location:"))
        self.label_4.setText(_translate("Form", "Image Data Augment:"))
        self.pushButton_5.setText(_translate("Form", "Generrate"))
import Icon.icon_rc